apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-node-affinity
  namespace: system-tools
data:
  nodeSelectorTerms: |
    - matchExpressions:
      - key: type
        operator: In
        values:
        - system